# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45b20f76c89745a698fd728ed3a40c32006f5ca4c9ae65a49dc6798303b9a0e83ef015d419c6761bc27fa6d954154ed9170ac0834c9edb6cff3a26d586fc016a

test:
  secret_key_base: 85b401a25e07f0a3fa4caae2fe06faad10ae53709f05a7ab17909a9e5cb6d67ce3d61655e5feee6b7166e294779623c4b492ba7a4932096462141d892321670a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
